name: Run pytest tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      JIRA_TOKEN: ${{ secrets.JIRA_TOKEN }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Print current directory
      run: |
        pwd
        ls -la

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Print contents of .env file
      run: cat .env

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Setup ChromeDriver
      uses: browser-actions/setup-chrome@latest
      with:
        chrome-version: latest

    - name: Set PYTHONPATH
      run: echo "PYTHONPATH=${{ github.workspace }}" >> $GITHUB_ENV

    - name: Run pytest for a specific script
      run: |
        pytest tests/api_ui_test_runner.py --html=report/report.html
      continue-on-error: true

    - name: Upload HTML report as artifact
      uses: actions/upload-artifact@v2
      with:
        name: pytest-html-report
        path: report
