name: Selenium Test
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      name: Checkout code

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable

    - name: Get Chrome version
      id: chrome_version
      run: |
        CHROME_VERSION_FULL=$(google-chrome --version | sed 's/Google Chrome //')
        CHROME_VERSION_MAJOR=$(echo "$CHROME_VERSION_FULL" | sed 's/\([0-9]*\)\..*/\1/')
        echo "CHROME_VERSION_FULL=$CHROME_VERSION_FULL" >> $GITHUB_ENV
        echo "CHROME_VERSION_MAJOR=$CHROME_VERSION_MAJOR" >> $GITHUB_ENV
        echo ::set-output name=CHROME_VERSION_MAJOR::$CHROME_VERSION_MAJOR
        
        
        
    - name: Install compatible ChromeDriver
      run: |
        CHROME_VERSION_MAJOR=${{ steps.chrome_version.outputs.CHROME_VERSION_MAJOR }}
        CHROMEDRIVER_VERSION=$(curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION_MAJOR")
        wget -N "http://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip" -P ~/
        unzip ~/chromedriver_linux64.zip -d ~/
        sudo mv -f ~/chromedriver /usr/local/bin/chromedriver
        sudo chown root:root /usr/local/bin/chromedriver
        sudo chmod 0755 /usr/local/bin/chromedriver
        chromedriver --version



    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium

    - name: Set PYTHONPATH
      run: echo "PYTHONPATH=${{ github.workspace }}" >> $GITHUB_ENV

    - name: Run tests
      run: python ui_test_runner.py
      working-directory: ./tests/ui_tests
