name: Selenium Test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      name: Checkout code

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium
      

    - name: Setup ChromeDriver
      uses: browser-actions/setup-chrome@v1
      with:
        chrome-version: latest

    - name: Set PYTHONPATH
      run: echo "PYTHONPATH=${{ github.workspace }}" >> $GITHUB_ENV


    - name: Run tests
      run: python ui_test_runner.py
      working-directory: ./tests/ui_tests
